Repository IntersectMBO/ouroboros-network, pull requests merged in 2023-03, with the labels that each got.

#4423 Add `Wunused-packages` to default `ghc-options` for consensus packages.
  .github/workflows/cabal.project.local.Linux
  ouroboros-consensus-byron-test/ouroboros-consensus-byron-test.cabal
  ouroboros-consensus-byron/ouroboros-consensus-byron.cabal
  ouroboros-consensus-byronspec/ouroboros-consensus-byronspec.cabal
  ouroboros-consensus-cardano-test/ouroboros-consensus-cardano-test.cabal
  ouroboros-consensus-cardano-tools/ouroboros-consensus-cardano-tools.cabal
  ouroboros-consensus-cardano/ouroboros-consensus-cardano.cabal
  ouroboros-consensus-mock-test/ouroboros-consensus-mock-test.cabal
  ouroboros-consensus-mock/ouroboros-consensus-mock.cabal
  ouroboros-consensus-protocol/ouroboros-consensus-protocol.cabal
  ouroboros-consensus-shelley-test/ouroboros-consensus-shelley-test.cabal
  ouroboros-consensus-shelley/ouroboros-consensus-shelley.cabal
  ouroboros-consensus-test/ouroboros-consensus-test.cabal
  ouroboros-consensus-tutorials/ouroboros-consensus-tutorials.cabal
  ouroboros-consensus/ouroboros-consensus.cabal
Labels: :handshake: consensus, 🔄 continuous-integration, dependencies

#4414 Enforce version bounds per-bundle and inter-bundle
  ouroboros-consensus-byron-test/ouroboros-consensus-byron-test.cabal
  ouroboros-consensus-byron/ouroboros-consensus-byron.cabal
  ouroboros-consensus-byronspec/changelog.d
  ouroboros-consensus-byronspec/ouroboros-consensus-byronspec.cabal
  ouroboros-consensus-cardano-test/ouroboros-consensus-cardano-test.cabal
  ouroboros-consensus-cardano-tools/ouroboros-consensus-cardano-tools.cabal
  ouroboros-consensus-cardano/changelog.d/20230228_130310_jasataco_enforce_bundle_constraints.md
  ouroboros-consensus-cardano/ouroboros-consensus-cardano.cabal
  ouroboros-consensus-diffusion/ouroboros-consensus-diffusion.cabal
  ouroboros-consensus-mock-test/ouroboros-consensus-mock-test.cabal
  ouroboros-consensus-mock/ouroboros-consensus-mock.cabal
  ouroboros-consensus-protocol/ouroboros-consensus-protocol.cabal
  ouroboros-consensus-shelley-test/ouroboros-consensus-shelley-test.cabal
  ouroboros-consensus-shelley/ouroboros-consensus-shelley.cabal
  ouroboros-consensus-test/ouroboros-consensus-test.cabal
  ouroboros-consensus-tutorials/changelog.d
  ouroboros-consensus-tutorials/ouroboros-consensus-tutorials.cabal
  ouroboros-consensus/CHANGELOG.md
  ouroboros-consensus/changelog.d/20230228_130303_jasataco_enforce_bundle_constraints.md
Labels: :handshake: consensus

#4421 Improve GHA situation
  .github/CODEOWNERS
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/build.yml
  .github/workflows/cabal.project.local.Linux
  .github/workflows/cabal.project.local.Windows
  .github/workflows/check-git-dependencies.yml
  .github/workflows/checks.yml
  .github/workflows/consensus-changelog-consistency.yml
  bors.toml
  cardano-ping/cardano-ping.cabal
  nix/cells/cloud/actions.nix
  scripts/ci/check-git-dependencies.sh
Labels: 🔄 continuous-integration

#4429 Remove `Test.Util.Classify` in favour of `Test.StateMachine.Labelling`.
  ouroboros-consensus-test/ouroboros-consensus-test.cabal
  ouroboros-consensus-test/src/Test/Util/Classify.hs
  ouroboros-consensus-test/test-storage/Test/Ouroboros/Storage/ChainDB/StateMachine.hs
  ouroboros-consensus-test/test-storage/Test/Ouroboros/Storage/FS/StateMachine.hs
  ouroboros-consensus-test/test-storage/Test/Ouroboros/Storage/ImmutableDB/StateMachine.hs
  ouroboros-consensus-test/test-storage/Test/Ouroboros/Storage/LedgerDB/OnDisk.hs
  ouroboros-consensus-test/test-storage/Test/Ouroboros/Storage/VolatileDB/StateMachine.hs
Labels: maintenance

#4467 Fix NonP2P to P2P interop problem
  ouroboros-network-framework/CHANGELOG.md
  ouroboros-network-framework/src/Ouroboros/Network/Server/ConnectionTable.hs
  ouroboros-network-framework/src/Ouroboros/Network/Socket.hs
  ouroboros-network-framework/src/Ouroboros/Network/Subscription/PeerState.hs
  ouroboros-network-framework/src/Ouroboros/Network/Subscription/Worker.hs
  ouroboros-network/CHANGELOG.md
  ouroboros-network/src/Ouroboros/Network/NodeToNode.hs
Labels: networking

#4474 Enable benchmark builds in GitHub Actions by default using `benchmarks: True`
  .github/workflows/cabal.project.local.Windows
  cabal.project
Labels: benchmarking, 🔄 continuous-integration

#4479 Introduce separate `index-state` for tools, simplify dependency on stylish-haskell
  CONTRIBUTING.md
  nix/local-config.nix
  nix/pkgs.nix
  nix/sources.json
  shell.nix
Labels: 🔄 continuous-integration

#4475 Use `fs-sim-0.1.0.0` and `fs-api-0.1.0.0`, update cabal `index-state`s
  cabal.project
  ouroboros-consensus/src/Ouroboros/Consensus/Util/Orphans.hs
Labels: dependencies

#4483 Fix misleading names in `estimateBlockSize` test
  ouroboros-consensus-test/src/Test/Util/Serialisation/Roundtrip.hs
Labels: :handshake: consensus, testing
