Repository IntersectMBO/ouroboros-network, pull requests merged in 2024-09, with the labels that each got.

#4953 coot/mermaid graph
  README.md
Labels: documentation

#4959 churn no timeouts fix
  ouroboros-network/src/Ouroboros/Network/PeerSelection/Churn.hs
Labels: churn

#4965 Updated SECURITY.md
  SECURITY.md
Labels: documentation

#4964 ouroboros-network.cabal
  ouroboros-network/demo/chain-sync.hs
  ouroboros-network/ouroboros-network.cabal
  ouroboros-network/sim-tests-lib/Ouroboros/Network/BlockFetch/Examples.hs
  ouroboros-network/sim-tests-lib/Ouroboros/Network/MockNode.hs
  ouroboros-network/sim-tests-lib/Test/Ouroboros/Network/BlockFetch.hs
  ouroboros-network/sim-tests-lib/Test/Ouroboros/Network/Diffusion/Node.hs
  ouroboros-network/sim-tests-lib/Test/Ouroboros/Network/Diffusion/Node/NodeKernel.hs
  ouroboros-network/sim-tests-lib/Test/Ouroboros/Network/Diffusion/Policies.hs
  ouroboros-network/sim-tests-lib/Test/Ouroboros/Network/KeepAlive.hs
  ouroboros-network/sim-tests-lib/Test/Ouroboros/Network/LedgerPeers.hs
  ouroboros-network/sim-tests-lib/Test/Ouroboros/Network/MockNode.hs
  ouroboros-network/sim-tests-lib/Test/Ouroboros/Network/PeerSelection/MockEnvironment.hs
  ouroboros-network/sim-tests-lib/Test/Ouroboros/Network/PeerSelection/PeerMetric.hs
  ouroboros-network/sim-tests-lib/Test/Ouroboros/Network/PeerSelection/RootPeersDNS.hs
  ouroboros-network/sim-tests-lib/Test/Ouroboros/Network/PeerState.hs
  ouroboros-network/sim-tests-lib/Test/Ouroboros/Network/Testnet.hs
  ouroboros-network/sim-tests-lib/Test/Ouroboros/Network/Testnet/Simulation/Node.hs
  ouroboros-network/sim-tests-lib/Test/Ouroboros/Network/TxSubmission.hs
Labels: maintenance

#4966 update project text on SECURITY.md
  SECURITY.md
Labels: documentation
