Repository IntersectMBO/ouroboros-network, pull requests merged in 2024-06, with the labels that each got.

#4872 Adds IOSimPOR diffusion tests
  .github/workflows/build.yml
  cabal.project
  cardano-ping/CHANGELOG.md
  cardano-ping/cardano-ping.cabal
  flake.lock
  network-mux/CHANGELOG.md
  network-mux/demo/mux-demo.hs
  network-mux/network-mux.cabal
  ntp-client/CHANGELOG.md
  ntp-client/ntp-client.cabal
  ouroboros-network-api/CHANGELOG.md
  ouroboros-network-api/ouroboros-network-api.cabal
  ouroboros-network-framework/CHANGELOG.md
  ouroboros-network-framework/ouroboros-network-framework.cabal
  ouroboros-network-framework/sim-tests/Test/Ouroboros/Network/Server2/Sim.hs
  ouroboros-network-protocols/CHANGELOG.md
  ouroboros-network-protocols/ouroboros-network-protocols.cabal
  ouroboros-network-testing/CHANGELOG.md
  ouroboros-network-testing/ouroboros-network-testing.cabal
  ouroboros-network/CHANGELOG.md
  ouroboros-network/ouroboros-network.cabal
  ouroboros-network/sim-tests-lib/Test/Ouroboros/Network/Testnet.hs
Labels: testing, technical debt, io-sim

#4848 Refactor ledgerPeersThread signature
  ouroboros-network/CHANGELOG.md
  ouroboros-network/src/Ouroboros/Network/PeerSelection/LedgerPeers.hs
Labels: DNS

#4849 Move functionality of calculating big ledger peers to ouroboros-network-api
  ouroboros-network-api/CHANGELOG.md
  ouroboros-network-api/ouroboros-network-api.cabal
  ouroboros-network-api/src/Ouroboros/Network/PeerSelection/LedgerPeers/Type.hs
  ouroboros-network-api/src/Ouroboros/Network/PeerSelection/LedgerPeers/Utils.hs
  ouroboros-network/CHANGELOG.md
  ouroboros-network/sim-tests-lib/Test/Ouroboros/Network/LedgerPeers.hs
  ouroboros-network/src/Ouroboros/Network/PeerSelection/LedgerPeers.hs
  ouroboros-network/src/Ouroboros/Network/PeerSelection/LedgerPeers/Common.hs
Labels: outbound-governor
