Repository IntersectMBO/ouroboros-network, pull requests merged in 2024-02, with the labels that each got.

#4793 Make PeerSharingController private
  ouroboros-network/CHANGELOG.md
  ouroboros-network/src/Ouroboros/Network/PeerSelection/PeerSelectionActions.hs
  ouroboros-network/src/Ouroboros/Network/PeerSharing.hs
Labels: peer-sharing

#4797 GHA: use enableCrossOsArchive
  .github/workflows/build.yml
Labels: CI

#4796 Fix comment: Duplex started in NodeToNodeV_10
  ouroboros-network/src/Ouroboros/Network/Diffusion/P2P.hs
Labels: documentation

#4799 Fix local roots clamp to trustable & changed LedgerPeersConsensusInterface function type signature
  ouroboros-network-api/CHANGELOG.md
  ouroboros-network-api/src/Ouroboros/Network/PeerSelection/LedgerPeers/Type.hs
  ouroboros-network/CHANGELOG.md
  ouroboros-network/sim-tests-lib/Test/Ouroboros/Network/LedgerPeers.hs
  ouroboros-network/sim-tests-lib/Test/Ouroboros/Network/PeerSelection/MockEnvironment.hs
  ouroboros-network/src/Ouroboros/Network/PeerSelection/Governor/Monitor.hs
  ouroboros-network/src/Ouroboros/Network/PeerSelection/LedgerPeers.hs
  ouroboros-network/src/Ouroboros/Network/PeerSelection/PeerSelectionActions.hs
Labels: bootstrap
