Repository IntersectMBO/ouroboros-network, pull requests merged in 2025-07, with the labels that each got.

#5147 Use strict pairs in network-mux IngressQueue
  network-mux/CHANGELOG.md
  network-mux/bench/socket_read_write/Main.hs
  network-mux/network-mux.cabal
  network-mux/src/Network/Mux.hs
  network-mux/src/Network/Mux/Ingress.hs
  network-mux/src/Network/Mux/Types.hs
Labels: mux

#5159 GHA: install cddlc
  .github/workflows/nightly.yml
Labels: CI

#5156 Moved NodeToNode and NodeToClient modules to cardano-diffusion
  cardano-client/cardano-client.cabal
  cardano-client/src/Cardano/Client/Subscription.hs
  decentralized-message-queue/decentralized-message-queue.cabal
  decentralized-message-queue/src/DMQ/Configuration.hs
  decentralized-message-queue/src/DMQ/Diffusion/Applications.hs
  decentralized-message-queue/src/DMQ/Diffusion/Arguments.hs
  decentralized-message-queue/src/DMQ/Diffusion/NodeKernel.hs
  decentralized-message-queue/src/DMQ/NodeToClient.hs
  decentralized-message-queue/src/DMQ/NodeToNode.hs
  ouroboros-network-framework/src/Ouroboros/Network/Snocket.hs
  ouroboros-network/CHANGELOG.md
  ouroboros-network/cardano-diffusion/Cardano/Network/Diffusion.hs
  ouroboros-network/cardano-diffusion/Cardano/Network/Diffusion/Configuration.hs
  ouroboros-network/cardano-diffusion/Cardano/Network/Diffusion/Types.hs
  ouroboros-network/cardano-diffusion/Cardano/Network/NodeToClient.hs
  ouroboros-network/cardano-diffusion/Cardano/Network/NodeToNode.hs
  ouroboros-network/demo/chain-sync.hs
  ouroboros-network/io-tests/Test/Ouroboros/Network/Socket.hs
  ouroboros-network/orphan-instances/Cardano/Network/OrphanInstances.hs
  ouroboros-network/orphan-instances/Ouroboros/Network/OrphanInstances.hs
  ouroboros-network/ouroboros-network.cabal
  ouroboros-network/sim-tests/Main.hs
  ouroboros-network/src/Ouroboros/Network/Diffusion.hs
  ouroboros-network/src/Ouroboros/Network/Diffusion/Configuration.hs
  ouroboros-network/src/Ouroboros/Network/Diffusion/Types.hs
  ouroboros-network/src/Ouroboros/Network/PeerSelection/PeerMetric.hs
  ouroboros-network/testlib/Ouroboros/Network/BlockFetch/Examples.hs
  ouroboros-network/testlib/Test/Cardano/Network/NodeToClient/Version.hs
  ouroboros-network/testlib/Test/Cardano/Network/NodeToNode/Version.hs
  ouroboros-network/testlib/Test/Cardano/Network/OrphanInstances/Tests.hs
  ouroboros-network/testlib/Test/Cardano/Network/Version.hs
  ouroboros-network/testlib/Test/Ouroboros/Network/Diffusion/Node/Kernel.hs
  ouroboros-network/testlib/Test/Ouroboros/Network/Diffusion/Node/MiniProtocols.hs
  ouroboros-network/testlib/Test/Ouroboros/Network/Diffusion/Testnet/Cardano.hs
  ouroboros-network/testlib/Test/Ouroboros/Network/TxSubmission.hs
Labels: dmq-node, cardano-diffusion

#5158 network-spec: fixed TxSubmision's MsgDone initial state
  docs/network-spec/miniprotocols.tex
Labels: documentation

#5167 Peer monitoring loop refactor
  ouroboros-network-api/src/Ouroboros/Network/PeerSelection/LedgerPeers/Type.hs
  ouroboros-network/cardano-diffusion/Cardano/Network/Diffusion.hs
  ouroboros-network/cardano-diffusion/Cardano/Network/Diffusion/Handlers.hs
  ouroboros-network/src/Ouroboros/Network/PeerSelection/Governor/Types.hs
  ouroboros-network/src/Ouroboros/Network/PeerSelection/PeerStateActions.hs
  ouroboros-network/testlib/Test/Ouroboros/Network/Diffusion/Testnet/Cardano.hs
Labels: technical debt
