Repository IntersectMBO/ouroboros-network, pull requests merged in 2025-08, with the labels that each got.

#5180 Improvements to the release script
  scripts/release-to-chap.sh
Labels: release

#5187 network-spec: relax requirement after `MsgIntersectFound`
  docs/network-spec/miniprotocols.tex
Labels: documentation

#5189 Propagate disconnection reason out of connection manager
  ouroboros-network-framework/CHANGELOG.md
  ouroboros-network-framework/demo/connection-manager.hs
  ouroboros-network-framework/sim-tests/Test/Ouroboros/Network/ConnectionManager.hs
  ouroboros-network-framework/src/Ouroboros/Network/ConnectionHandler.hs
  ouroboros-network-framework/src/Ouroboros/Network/ConnectionManager/Core.hs
  ouroboros-network-framework/src/Ouroboros/Network/ConnectionManager/Types.hs
  ouroboros-network-framework/src/Ouroboros/Network/Protocol/Handshake.hs
  ouroboros-network-framework/testlib/Test/Ouroboros/Network/ConnectionManager/Experiments.hs
  ouroboros-network/src/Ouroboros/Network/Diffusion.hs
  ouroboros-network/src/Ouroboros/Network/Diffusion/Types.hs
  ouroboros-network/src/Ouroboros/Network/PeerSelection/PeerStateActions.hs
Labels: exception handling, tracing
