Repository IntersectMBO/ouroboros-network, pull requests merged in 2025-01, with the labels that each got.

#5029 ouroboros-network-0.19 release
  cardano-client/CHANGELOG.md
  cardano-client/cardano-client.cabal
  cardano-ping/CHANGELOG.md
  cardano-ping/cardano-ping.cabal
  network-mux/CHANGELOG.md
  network-mux/network-mux.cabal
  ouroboros-network-api/CHANGELOG.md
  ouroboros-network-api/ouroboros-network-api.cabal
  ouroboros-network-framework/CHANGELOG.md
  ouroboros-network-framework/ouroboros-network-framework.cabal
  ouroboros-network-protocols/CHANGELOG.md
  ouroboros-network-protocols/ouroboros-network-protocols.cabal
  ouroboros-network-testing/CHANGELOG.md
  ouroboros-network-testing/ouroboros-network-testing.cabal
  ouroboros-network/CHANGELOG.md
  ouroboros-network/ouroboros-network.cabal
  scripts/build-with-chap.sh
  scripts/release-to-chap.sh
Labels: release

#5025 add mapTraceFetchClientState
  ouroboros-network/CHANGELOG.md
  ouroboros-network/src/Ouroboros/Network/BlockFetch/ClientState.hs
Labels: block-fetch

#5030 Use network-3.2.7
  cardano-ping/cardano-ping.cabal
  network-mux/network-mux.cabal
  ntp-client/ntp-client.cabal
  ouroboros-network-api/ouroboros-network-api.cabal
  ouroboros-network-framework/ouroboros-network-framework.cabal
  ouroboros-network/ouroboros-network.cabal
Labels: maintenance

#5036 Network Spec Update
  docs/network-spec/miniprotocols.tex
  docs/network-spec/mux.tex
  docs/network-spec/network-spec.tex
  ouroboros-network-protocols/CHANGELOG.md
  ouroboros-network-protocols/cddl/specs/handshake-node-to-node-v13.cddl
  ouroboros-network-protocols/src/Ouroboros/Network/Protocol/BlockFetch/Type.hs
  ouroboros-network-protocols/src/Ouroboros/Network/Protocol/ChainSync/Type.hs
  ouroboros-network-protocols/src/Ouroboros/Network/Protocol/LocalTxMonitor/Type.hs
  ouroboros-network-protocols/src/Ouroboros/Network/Protocol/LocalTxSubmission/Type.hs
  ouroboros-network-protocols/src/Ouroboros/Network/Protocol/PeerSharing/Type.hs
  ouroboros-network-protocols/src/Ouroboros/Network/Protocol/TxSubmission2/Type.hs
  scripts/prologue
Labels: documentation

#5044 network-spec: language
  docs/network-spec/architecture.tex
  docs/network-spec/connection-manager.tex
  docs/network-spec/miniprotocols.tex
  docs/network-spec/mux.tex
  docs/network-spec/network-spec.tex
Labels: documentation

#5053 network-spec: small improvements
  docs/network-spec/miniprotocols.tex
  ouroboros-network-protocols/cddl/specs/tx-submission2.cddl
Labels: documentation

#5048 New start strategy for miniprotocols
  network-mux/CHANGELOG.md
  network-mux/src/Network/Mux.hs
  network-mux/src/Network/Mux/Trace.hs
  network-mux/src/Network/Mux/Types.hs
  network-mux/test/Test/Mux.hs
  ouroboros-network-framework/CHANGELOG.md
  ouroboros-network-framework/demo/connection-manager.hs
  ouroboros-network-framework/demo/ping-pong.hs
  ouroboros-network-framework/io-tests/Test/Ouroboros/Network/Socket.hs
  ouroboros-network-framework/io-tests/Test/Ouroboros/Network/Subscription.hs
  ouroboros-network-framework/sim-tests/Test/Ouroboros/Network/Socket.hs
  ouroboros-network-framework/sim-tests/Test/Ouroboros/Network/Subscription.hs
  ouroboros-network-framework/src/Ouroboros/Network/InboundGovernor.hs
  ouroboros-network-framework/src/Ouroboros/Network/InboundGovernor/Event.hs
  ouroboros-network-framework/src/Ouroboros/Network/Mux.hs
  ouroboros-network-framework/testlib/Test/Ouroboros/Network/ConnectionManager/Experiments.hs
  ouroboros-network/CHANGELOG.md
  ouroboros-network/demo/chain-sync.hs
  ouroboros-network/io-tests/Test/Ouroboros/Network/Pipe.hs
  ouroboros-network/io-tests/Test/Ouroboros/Network/Socket.hs
  ouroboros-network/sim-tests-lib/Test/Ouroboros/Network/Mux.hs
  ouroboros-network/sim-tests-lib/Test/Ouroboros/Network/Testnet/Node/MiniProtocols.hs
  ouroboros-network/src/Ouroboros/Network/Diffusion/NonP2P.hs
  ouroboros-network/src/Ouroboros/Network/NodeToClient.hs
  ouroboros-network/src/Ouroboros/Network/NodeToNode.hs
Labels: mux
